all : 
	cd ./elifeFigure1/ && make 
	cd ./elifeFigure2/ && make 
	cd ./elifeFigure3/ && make 
	cd ./elifeFigure4/ && make 
	cd ./elifeFigure5/ && make 
	cd ./elifeFigure6/ && make 
	cd ./elifeFigure7/ && make 
	cd ./suppl && make
